### ISSUE TITLE
Local dev setup seems to be broken

### ISSUE THREAD

**Issue by aaronlippold** [fiction-com/factor#81]
Went through the basic setup steps. Running a local docker mongodb server on 27017. 

Had to set the DB_CONNECTION to `mongodb://localhost:27017/test1` as the setup didn't ask me for a db name but would throw a `db name must be a string error` without it.

```
Setup Needed
    SMTP Email Credentials
    Plugin: S3 Storage Credentials
  Run 'yarn factor setup'


❯ Starting Server...
    URL: http://localhost:3000
    NODE_ENV: development
    FACTOR_ENV: development
    FACTOR_COMMAND: dev
    CWD: /Users/aaronl/github/mitre/test

✔ Built 15.99s
↑↓ Ready                                                                                                             14:36:38
Duplicate filter signature detected adding to "page-templates" filter.
Set "key" option to a unique value or set "reloads" true to silence this warning.
Duplicate filter signature detected adding to "content-routes" filter.
Set "key" option to a unique value or set "reloads" true to silence this warning.
Factor Server Error  @[/]
RangeError: Maximum call stack size exceeded
    at invokeWithErrorHandling (/Users/aaronl/github/mitre/test/node_modules/vue/dist/vue.runtime.common.dev.js:1858:5)
    at callHook (/Users/aaronl/github/mitre/test/node_modules/vue/dist/vue.runtime.common.dev.js:4201:7)
    at VueComponent.Vue._init (/Users/aaronl/github/mitre/test/node_modules/vue/dist/vue.runtime.common.dev.js:4979:5)
    at new VueComponent (/Users/aaronl/github/mitre/test/node_modules/vue/dist/vue.runtime.common.dev.js:5128:12)
    at createComponentInstanceForVnode (/Users/aaronl/github/mitre/test/node_modules/vue-server-renderer/build.dev.js:8169:10)
    at renderComponentInner (/Users/aaronl/github/mitre/test/node_modules/vue-server-renderer/build.dev.js:8393:40)
    at renderComponent (/Users/aaronl/github/mitre/test/node_modules/vue-server-renderer/build.dev.js:8368:5)
    at renderNode (/Users/aaronl/github/mitre/test/node_modules/vue-server-renderer/build.dev.js:8279:5)
    at resolve (/Users/aaronl/github/mitre/test/node_modules/vue-server-renderer/build.dev.js:8406:5)
    at waitForServerPrefetch (/Users/aaronl/github/mitre/test/node_modules/vue-server-renderer/build.dev.js:8272:3)
    at renderComponentInner (/Users/aaronl/github/mitre/test/node_modules/vue-server-renderer/build.dev.js:8411:3)
    at renderComponent (/Users/aaronl/github/mitre/test/node_modules/vue-server-renderer/build.dev.js:8368:5)
    at renderNode (/Users/aaronl/github/mitre/test/node_modules/vue-server-renderer/build.dev.js:8279:5)
    at resolve (/Users/aaronl/github/mitre/test/node_modules/vue-server-renderer/build.dev.js:8406:5)
    at waitForServerPrefetch (/Users/aaronl/github/mitre/test/node_modules/vue-server-renderer/build.dev.js:8272:3)
    at renderComponentInner (/Users/aaronl/github/mitre/test/node_modules/vue-server-renderer/build.dev.js:8411:3)
    at renderComponent (/Users/aaronl/github/mitre/test/node_modules/vue-server-renderer/build.dev.js:8368:5)
    at renderNode (/Users/aaronl/github/mitre/test/node_modules/vue-server-renderer/build.dev.js:8279:5)
    at resolve (/Users/aaronl/github/mitre/test/node_modules/vue-server-renderer/build.dev.js:8406:5)
    at waitForServerPrefetch (/Users/aaronl/github/mitre/test/node_modules/vue-server-renderer/build.dev.js:8272:3)
    at renderComponentInner (/Users/aaronl/github/mitre/test/node_modules/vue-server-renderer/build.dev.js:8411:3)
    at renderComponent (/Users/aaronl/github/mitre/test/node_modules/vue-server-renderer/build.dev.js:8368:5)
↑↓ Request: / 3.447s Size: 0kb GET:500```

**Comment by arpowers** [comment]
@aaronlippold hey aaron, did you get this using the repo or did you install using create-factor-app ?

**Comment by arpowers** [comment]
we're in the process of setting up the testing suite right now, its possible we need to republish the packages.

**Comment by aaronlippold** [comment]
used this via the create-factor-app npx method. I can try via the repo as well. alpha.20 is what the cli installed.

**Comment by aaronlippold** [comment]
Some notes on the setup helper process:
1. If the mongodb needs a dbname that should also be in the DB string
2. if SES and S3 bucket are really required, that also should be in the setup tool
3. perhaps the default pattern should be to use the ~/.aws/ defaults and perhaps AWS Profiles to get the aws creds - less chance of committing them by accident.
4. A suggestion, for the initial user, a full docker setup - mongo, etc may be the most useful - then when you get to phase 2 - we can setup Atlas, SES etc.

**Comment by aaronlippold** [comment]
I can try doing a pull to see if that resolves my issues

**Comment by aaronlippold** [comment]
```├─ @factor/app-config@1.0.0-beta.4
├─ @factor/app-extend@1.0.0-beta.4
├─ @factor/app-fallbacks@1.0.0-beta.4
├─ @factor/app-meta@1.0.0-beta.4
├─ @factor/app-router@1.0.0-beta.4
├─ @factor/app-settings@1.0.0-beta.4
├─ @factor/app-store@1.0.0-beta.4
├─ @factor/build-config@1.0.0-beta.4
├─ @factor/build-files@1.0.0-beta.4
├─ @factor/build-transpiler@1.0.0-beta.4
├─ @factor/build-webpack@1.0.0-beta.4
├─ @factor/core-db@1.0.0-beta.4
├─ @factor/core-email@1.0.0-beta.4
├─ @factor/core-endpoint@1.0.0-beta.4
├─ @factor/core-error@1.0.0-beta.4
├─ @factor/core-log@1.0.0-beta.4
├─ @factor/core-storage@1.0.0-beta.4
├─ @factor/core-theme@1.0.0-beta.4
├─ @factor/core-user-dashboard@1.0.0-beta.4
├─ @factor/core-user-emails@1.0.0-beta.4
├─ @factor/core-user-roles@1.0.0-beta.4
├─ @factor/core-user@1.0.0-beta.4
├─ @factor/core@1.0.0-beta.4
├─ @factor/dashboard@1.0.0-beta.4
├─ @factor/metatags@1.0.0-beta.4
├─ @factor/paths@1.0.0-beta.4
├─ @factor/plugin-ssr-bar@1.0.0-beta.4
├─ @factor/post-page-templates@1.0.0-beta.4
├─ @factor/server-config@1.0.0-beta.4
├─ @factor/server-dev@1.0.0-beta.4
├─ @factor/server-extend@1.0.0-beta.4
├─ @factor/server@1.0.0-beta.4
├─ @factor/setup@1.0.0-beta.4
├─ @factor/tools-http@1.0.0-beta.4
├─ @factor/tools-markdown@1.0.0-beta.4
├─ @factor/tools-mongo@1.0.0-beta.4
├─ @factor/tools-time@1.0.0-beta.4
├─ @factor/ui-directives-standard@1.0.0-beta.4```

**Comment by aaronlippold** [comment]
Cool. I'll let you guys hack and when you're ready for me to do an update and test again I'm happy to be your guinea pig

**Comment by arpowers** [comment]
@aaronlippold your feedback would be super helpful.  Once we have a bit more code coverage (especially testing of install!) then we'll be opening up the "developer program," etc. 

We'd love to have you involved, please send me an email at andrew@fiction.com and we can chat.
