### ISSUE TITLE
`create-factor-app` v.1.0.0-beta.6  is broken

### ISSUE THREAD

**Issue by sjke** [fiction-com/factor#84]
**Reason for this issue**
```bash
~/workspace/tests  yarn create factor-app cr

yarn create v1.19.1
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
success Installed "create-factor-app@1.0.0-beta.6" with binaries:
      - create-factor-app
❯ Starting create-factor-app@1.0.0-beta.6                                                                                                                     11:57:19

✔ Great work! Generating Factor project in: /Users/sjke/workspace/tests/cr                                                                                    11:57:19


 ERROR  superb is not a function                                                                                                                              11:57:19

  at Object.<anonymous> (/Users/sjke/.config/yarn/global/node_modules/create-factor-app/saofile.js:18:22)
  at Module._compile (internal/modules/cjs/loader.js:816:30)
  at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
  at Module.load (internal/modules/cjs/loader.js:685:32)
  at Function.Module._load (internal/modules/cjs/loader.js:620:12)
  at Module.require (internal/modules/cjs/loader.js:723:19)
  at require (internal/modules/cjs/helpers.js:14:16)
  at /Users/sjke/.config/yarn/global/node_modules/joycon/lib/index.js:250:19
  at Generator.next (<anonymous>)
  at asyncGeneratorStep (/Users/sjke/.config/yarn/global/node_modules/joycon/lib/index.js:14:103)

error Command failed.
Exit code: 1
Command: /usr/local/bin/create-factor-app
Arguments: cr
Directory: /Users/sjke/workspace/tests
Output:

info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.
```

**Steps to Reproduce**
`yarn create factor-app <project-name>` or `npx create-factor-app <project-name>`

**Comment by halilertekin** [comment]
+1

**Comment by arpowers** [comment]
sup guys, thanks for (attempting) to give it a try. We're currently working on a massive refactor which includes 200+ test cases; in the `refactor/modules` branch. 

Once that's relatively stable (eta 2 weeks), the plan is to go to public beta and continue to work on stability for a while as most features have already been implemented. 

That would be the ideal time to give things a try, and we definitely don't want to lose your attention. I'll be reaching out once we feel that Factor is 100% elegant, useful and will have indefinite stability in production.

**Comment by jprando** [comment]
+1
